// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import ()

type Story struct {
	ID            string
	UserID        string
	PartyID       string
	Url           string
	TaggedFriends []string
}
