// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import (
	"context"
)

type Querier interface {
	CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error)
	DeleteStory(ctx context.Context, arg DeleteStoryParams) error
	GetStory(ctx context.Context, id string) (Story, error)
	GetStoryByParty(ctx context.Context, arg GetStoryByPartyParams) ([]Story, error)
	GetStoryByUser(ctx context.Context, arg GetStoryByUserParams) ([]Story, error)
}

var _ Querier = (*Queries)(nil)
